### get-test

GET http://localhost:3000/api/get-test
x-api-key: your_api_key_here

### save-test

POST http://localhost:3000/api/post-test
x-api-key: your_api_key_here
Content-Type: application/json

{
    "candidateId": "8wyEeI2zorA9uz9kv1nv",
    "answers": [
        [
            1,
            1
        ],
        [
            2,
            2
        ],
        [
            3,
            3
        ],
        [
            4,
            0
        ],
        [
            5,
            1
        ],
        [
            6,
            2
        ],
        [
            7,
            3
        ],
        [
            8,
            2
        ],
        [
            9,
            1
        ],
        [
            10,
            2
        ],
        [
            11,
            3
        ],
        [
            12,
            2
        ],
        [
            13,
            1
        ],
        [
            14,
            2
        ],
        [
            15,
            3
        ],
        [
            16,
            2
        ],
        [
            17,
            1
        ],
        [
            18,
            2
        ],
        [
            19,
            3
        ],
        [
            20,
            2
        ]
    ]
}

### post-candidate

POST http://localhost:3000/api/post-candidate
x-api-key: your_api_key_here
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com"
}

### get-question

GET http://localhost:3000/api/get-question
x-api-key: your_api_key_here

### post-question

POST http://localhost:3000/api/post-question
x-api-key: your_api_key_here
Content-Type: application/json

{
    "candidateId": "8wyEeI2zorA9uz9kv1nv",
    "answers": [
        [
            0,
            "answer 1"
        ],
        [
            1,
            "answer 2"
        ],
        [
            2,
            "answer 3"
        ]
    ]
}